#!/usr/bin/env python3
"""Fetch HSL city-bike stations and render the application's JavaScript data."""

import argparse
import json
import math
import os
import sys
import urllib.error
import urllib.request
from pathlib import Path


DEFAULT_ENDPOINT = "https://api.digitransit.fi/routing/v2/hsl/gtfs/v1"
QUERY = """{
  vehicleRentalStations {
    stationId
    name
    lat
    lon
  }
}"""


def normalize_station(raw):
    if not isinstance(raw, dict):
        raise ValueError("Digitransit returned an invalid station entry")
    station_id = raw.get("stationId")
    if not isinstance(station_id, str) or not station_id.startswith("smoove:"):
        return None

    numeric_id = station_id.removeprefix("smoove:")
    if not numeric_id.isdigit():
        raise ValueError(f"invalid Smoove station ID: {station_id!r}")

    name = raw.get("name")
    if not isinstance(name, str) or not name.strip():
        raise ValueError(f"station {station_id!r} has no name")

    coordinates = []
    for field in ("lat", "lon"):
        value = raw.get(field)
        if isinstance(value, bool):
            raise ValueError(f"station {station_id!r} has invalid {field}")
        try:
            value = float(value)
        except (TypeError, ValueError) as error:
            raise ValueError(f"station {station_id!r} has invalid {field}") from error
        if not math.isfinite(value):
            raise ValueError(f"station {station_id!r} has invalid {field}")
        coordinates.append(value)

    latitude, longitude = coordinates
    if not -90 <= latitude <= 90 or not -180 <= longitude <= 180:
        raise ValueError(f"station {station_id!r} has out-of-range coordinates")
    return [int(numeric_id), name.strip(), latitude, longitude]


def parse_response(payload):
    if not isinstance(payload, dict):
        raise ValueError("Digitransit returned a non-object response")
    if payload.get("errors"):
        messages = "; ".join(str(error.get("message", error)) for error in payload["errors"])
        raise ValueError(f"Digitransit GraphQL error: {messages}")
    try:
        raw_stations = payload["data"]["vehicleRentalStations"]
    except (KeyError, TypeError) as error:
        raise ValueError("Digitransit response contains no vehicleRentalStations") from error
    if not isinstance(raw_stations, list):
        raise ValueError("Digitransit vehicleRentalStations is not a list")

    stations = [station for raw in raw_stations if (station := normalize_station(raw)) is not None]
    if not stations:
        raise ValueError("Digitransit returned no Smoove bike stations")
    stations.sort(key=lambda station: station[0])
    duplicates = [left[0] for left, right in zip(stations, stations[1:]) if left[0] == right[0]]
    if duplicates:
        raise ValueError(f"duplicate normalized station ID: {duplicates[0]}")
    return stations


def fetch_stations(endpoint, subscription_key):
    body = json.dumps({"query": QUERY}).encode()
    request = urllib.request.Request(
        endpoint,
        data=body,
        headers={
            "Content-Type": "application/json",
            "digitransit-subscription-key": subscription_key,
            "User-Agent": "kaupunkipyorat-station-builder/1.0",
        },
    )
    try:
        with urllib.request.urlopen(request, timeout=30) as response:
            payload = json.load(response)
    except urllib.error.HTTPError as error:
        raise RuntimeError(f"Digitransit request failed with HTTP {error.code}") from error
    except (urllib.error.URLError, TimeoutError) as error:
        reason = getattr(error, "reason", error)
        raise RuntimeError(f"Digitransit request failed: {reason}") from error
    except (UnicodeDecodeError, json.JSONDecodeError) as error:
        raise RuntimeError("Digitransit returned invalid JSON") from error
    return parse_response(payload)


def render(stations):
    lines = [
        "// Generated by preprocess/build-stations.py; do not edit manually.",
        "// IDs and coordinates come from the Digitransit HSL Routing API.",
        "const STATIONS = [",
    ]
    for station_id, name, latitude, longitude in stations:
        encoded_name = json.dumps(name, ensure_ascii=False)
        lines.append(f"  [{station_id}, {encoded_name}, {latitude!r}, {longitude!r}],")
    lines[-1] = lines[-1].removesuffix(",")
    lines.append("];\n")
    return "\n".join(lines)


def write_output(path, contents):
    path.parent.mkdir(parents=True, exist_ok=True)
    temporary = path.with_name(f".{path.name}.tmp")
    temporary.write_text(contents, encoding="utf-8")
    temporary.replace(path)


def main(argv=None):
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("output", type=Path, help="JavaScript file to create")
    parser.add_argument("--endpoint", default=DEFAULT_ENDPOINT)
    args = parser.parse_args(argv)
    subscription_key = os.environ.get("DIGITRANSIT_SUBSCRIPTION_KEY")
    if not subscription_key:
        parser.error("DIGITRANSIT_SUBSCRIPTION_KEY is required")

    try:
        stations = fetch_stations(args.endpoint, subscription_key)
        write_output(args.output, render(stations))
    except (RuntimeError, ValueError, OSError) as error:
        print(f"error: {error}", file=sys.stderr)
        return 1
    print(f"Wrote {len(stations)} Smoove stations to {args.output}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
